#!/bin/sh

### BEGIN INIT INFO
# Provides:             etiny-server
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    eTiny - Web Client of the OpenERP
# Description:          OpenERP is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/start-tinyerp
NAME=etiny-server
DESC=etiny-server

test -x $DAEMON || exit 0

set -e

# Specify the user name (Default: terp).
USER="terp"

# Specify an alternate config file (Default: /etc/etiny-server.cfg).
CONFIGFILE="/etc/etiny-server.cfg"

# Additional options that are passed to the Daemon.
DAEMON_OPTS="$CONFIGFILE"

case "$1" in
    start)
        echo -n "Starting $DESC: "

        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
            --chuid $USER --background --make-pidfile \
            --exec $DAEMON -- $DAEMON_OPTS

        echo "$NAME."
        ;;

    stop)
        echo -n "Stopping $DESC: "

        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
            --oknodo

        echo "$NAME."
        ;;

    restart|force-reload)
        echo -n "Restarting $DESC: "

        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
            --oknodo

        sleep 1

        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
            --chuid $USER --background --make-pidfile \
            --exec $DAEMON -- $DAEMON_OPTS

        echo "$NAME."
        ;;

    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

# vim: sts=4 st=4 et

