#!/usr/bin/env python

import sys

from pkg_resources import Requirement, resource_filename
dirname = resource_filename(Requirement.parse('openerp-web'), 'openerp-web')

sys.path = [dirname] + sys.path

from openobject.commands import start, ConfigurationError

if __name__ == "__main__":
    try:
        start()
    except ConfigurationError, exc:
        sys.stderr.write(str(exc)+"\n")
        sys.exit(1)

# vim: ts=4 sts=4 sw=4 si et

